name: build-dotnet

on:
  workflow_call:
    inputs:
      net_version:
        description: 'Versión de .NET a utilizar'
        type: string
        required: true
        default: '6.0'
      net_framework:
        type: string
        description: 'Framework de .NET a utilizar (aspnet, console, etc.)'
        required: true
        default: 'console'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building .NET project..."
