name: build

on:
  push:
  merge_group:

permissions:
  contents: write

jobs:
  build:
    uses: './.github/workflows/common-build.yml'
    with:
      language: 'dotnet'
      net_version: '6.0'
      net_framework: 'console'
