name: build

on:
  push:
  merge_group:

jobs:
  build:
    uses: './.github/workflows/common-build.yml'
    with:
      language: 'dotnet'
      net_version: '6.0'
      net_framework: 'console'

  release:
    runs-on: ubuntu-latest
    # needs: build
    permissions:
      # actions: write
      # attestations: write
      # checks: write
      contents: write
      # deployments: write
      pull-requests: write
      # issues: write
      # statuses: write
      # discussions: write
      # packages: write
      # id-token: write
      # pages: write
      # security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: release-it
        run: |
          set -ex
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          npm install -g release-it --force
          release-it prerelease --ci

      # - name: Changelog generation
      #   # TODO: Compare against the correct branch or commit
      #   run: |
      #     git tag
      #     git tag -d v1.0.0 || true
      #     git tag v1.0.0

      # - uses: googleapis/release-please-action@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     release-type: simple
      #     skip-github-pull-request: true
      #     skip-github-release: false

      - uses: convco/convco-action@v0.2.0
        with:
          convco_version: 'latest'

      - name: Changelog generation
        # TODO: Compare against the correct branch or commit
        run: |
          export VERSION=$(git tag | tail -1)
          convco changelog -m1 $VERSION | tee CHANGELOG.md

      - name: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          # TODO: Set the tag name for your release
          tag_name: ${{ env.VERSION }}
          draft: false
          prerelease: true
          # TODO: Add the path to your release assets
          files: |
            action.yml
            README.md
