name: build-node

on:
  workflow_call:
    inputs:
      language:
        description: 'Programming language to use (node, dotnet, etc.)'
        type: string
        required: true
        default: 'node'
      node_version:
        description: 'Node.js version to use'
        type: string
        required: true
        default: '16.x'
      node_framework:
        description: 'Node.js framework to use (angular, react, vue, etc.)'
        required: true
        type: string
        default: 'none'
  merge_group:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate node version
        run: echo "Validating node version ${{ inputs.node_version }} and framework ${{ inputs.node_framework }}"

  build-node:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Build
        run: echo "Building node project..."

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Test
        run: echo "Running tests for .NET project..."
