name: deploy

on:
  pull_request_target:
    branches:
      - main
      - master

jobs:
  build:
    uses: './.github/workflows/common-build-dotnet.yml'
    with:
      language: 'dotnet'
      net_version: '6.0'
      net_framework: 'console'

  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Desplegando..."
