name: deploy

on:
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the project..."
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Desplegando..."
