name: deploy

on:
  pull_request_target:
    branches:
      - main
      - master

jobs:
  build:
    # TODO: Must support multiple languages
    uses: './.github/workflows/common-build-dotnet.yml'
    with:
      language: 'dotnet'
      net_version: '6.0'
      net_framework: 'console'

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: convco/convco-action@v0.2.0
        with:
          convco_version: 'latest'

      - name: Convco check
        # TODO: Compare against the correct branch or commit
        run: convco changelog > CHANGELOG.md

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          # TODO: Set the tag name for your release
          tag_name: v1.0.0
          draft: false
          prerelease: true
          # TODO: Add the path to your release assets
          files: |
            action.yml
            README.md

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Desplegando..."
