name: deploy

on:
  pull_request_target:
    branches:
      - main
      - master

jobs:
  build:
    uses: './.github/workflows/common-build-dotnet.yml'
    with:
      language: 'dotnet'
      net_version: '6.0'
      net_framework: 'console'

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release
        run: echo "Creating a release..."

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Desplegando..."
