name: deploy

on:
  pull_request_target:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    # TODO: Must support multiple languages
    uses: './.github/workflows/common-build-dotnet.yml'
    with:
      language: 'dotnet'
      net_version: '6.0'
      net_framework: 'console'

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: convco/convco-action@v0.2.0
        with:
          convco_version: 'latest'

      - uses: convco/convco-action@v0.2.0
        with:
          convco_version: 'latest'

      - name: Changelog generation
        # TODO: Compare against the correct branch or commit
        run: |
          git tag -d v1.0.0 || true
          git tag v1.0.0
          git push origin v1.0.0 --force || true
          convco changelog -m 1 v1.0.0 | tee CHANGELOG.md

      - name: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          # TODO: Set the tag name for your release
          tag_name: v1.0.0
          draft: false
          prerelease: true
          # TODO: Add the path to your release assets
          files: |
            action.yml
            README.md

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Desplegando..."
